---
apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: firebase-steam
  name: typescript-builder
  namespace: firebase-login
spec:
  dockerImageRepository: docker.io/kamshak/s2i-typescript
---
apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: firebase-steam
  name: node
  namespace: firebase-login
spec:
  dockerImageRepository: docker.io/library/node
  tags:
    -
      name: 8-alpine
      annotations: null
      from:
        kind: DockerImage
        name: 'docker.io/library/node:8-alpine'
      importPolicy: {  }
